<a href="https://colab.research.google.com/github/dsj12960/neural_assign_3/blob/main/assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Employee:
    Emp_Count = 0  
    Total_Salary = 0

    def __init__(self, name, family, salary, department):  # initializing the constructor  
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.Emp_Count += 1
        Employee.Total_Salary += salary
        # return name, family, salary, department, Employee.Emp_Count

    def avg_salary(self):  # function to calculate average salary
        avg_salary = Employee.Total_Salary / Employee.Emp_Count
        return avg_salary


class Full_time_Emp(Employee):  # Full Time Employee class inheriting the Employee class

    def __init__(self, name, family, salary, department, emp_type):
        Employee.__init__(self, name, family, salary, department)
        self.emp_type = emp_type
        # return emp_type


E1 = Employee("jasti", "1", 100000, "data_engineeing")
E2 = Employee("divya", "2", 200000, "testing")
E3 = Employee("ajay", "3", 300000, "Development")

F1 = Full_time_Emp("jasti", "2", 300000, "software", "Full Time")
F2 = Full_time_Emp("divya", "3", 200000, "hardware", "Intern")
F3 = Full_time_Emp("ajay", "6", 100000, "backend", "Contract")

print("Total Number of Employees are:", Employee.Emp_Count)
print("Total Salary given to Employees:", Employee.Total_Salary)
print("Average Salary is:", F3.avg_salary())  # invoking avg_salary function by using the instance

Total Number of Employees are: 6
Total Salary given to Employees: 1200000
Average Salary is: 200000.0


In [ ]:
import numpy as np

a = np.random.uniform(1, 20, 20)  # creating the random vector of size 20 having only float in the range 1-20
print('Random vector of size  20: \n', a)
b = a.reshape((4, 5))  # reshaping the array to 4 by 5
print('Reshaping the  array to 4 by 5: \n', b)
c = np.where(b == np.amax(b, axis=1).reshape(-1, 1), 0, b)  # replace the max in each row by 0(axis=1)
print('Replacing the  maximum in each row by 0: \n', c)

Random vector of size  20: 
 [19.10808784  6.14643291  1.04445146  4.58969611 10.98937415 19.41221167
 17.56330308 16.07877699 17.08863988 19.43055264  7.11856892 17.60152331
 14.83831881 13.73695446  5.99473962 13.74141749 18.39503605 15.90932716
 18.09285138  5.51109059]
Reshaping the  array to 4 by 5: 
 [[19.10808784  6.14643291  1.04445146  4.58969611 10.98937415]
 [19.41221167 17.56330308 16.07877699 17.08863988 19.43055264]
 [ 7.11856892 17.60152331 14.83831881 13.73695446  5.99473962]
 [13.74141749 18.39503605 15.90932716 18.09285138  5.51109059]]
Replacing the  maximum in each row by 0: 
 [[ 0.          6.14643291  1.04445146  4.58969611 10.98937415]
 [19.41221167 17.56330308 16.07877699 17.08863988  0.        ]
 [ 7.11856892  0.         14.83831881 13.73695446  5.99473962]
 [13.74141749  0.         15.90932716 18.09285138  5.51109059]]
